os: linux
env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5 LD=ld.gold
# We set language to generic so that Travis doesn't fall back to old compilers
language: generic
addons:
  apt:
    packages:
      - g++-5
      - cmake-data
      - cmake
      - binutils
      - binutils-gold
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test

before_install:
  # Fetch external submodule dependencies
  - git submodule init
  - git submodule update

  # Install Eigen by copying header files to a system include directory
  - wget -q http://bitbucket.org/eigen/eigen/get/3.2.10.tar.bz2
  - tar -xf 3.2.10.tar.bz2
  - cd eigen-eigen*
  - sudo cp -R Eigen /usr/local/include/Eigen

script:
  - cd $TRAVIS_BUILD_DIR
  - mkdir -p target/debug target/release

  # Debug build
  - cd $TRAVIS_BUILD_DIR/target/debug
  - cmake $TRAVIS_BUILD_DIR -DCMAKE_BUILD_TYPE=Debug
  - make check

  # Release build. There has been at least one case where the release
  # build failed, but the debug one did not.
  - cd $TRAVIS_BUILD_DIR/target/release
  - cmake $TRAVIS_BUILD_DIR -DCMAKE_BUILD_TYPE=Release
  - make check



